name: flutter_onfido
description: Onfido SDK plugin for Flutter. Package supports iOS and Android to verify users identity.
version: 0.2.5
homepage: https://github.com/geweald/flutter_onfido

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: '>=1.12.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.fluencybank.flutter_onfido
        pluginClass: FlutterOnfidoPlugin
      ios:
        pluginClass: FlutterOnfidoPlugin
